apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pedelogo
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup mongo-service.pedelogo.svc.cluster.local; do echo Database waiting; sleep 2; done']
      containers:
        - name: api
          image: julioesf/pedelogo-catalogo:{{tag}}
          # image: kubedevjesf.azurecr.io/pedelogo-catalogo:v1.0.0
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 32Mi
              cpu: 150m
            limits:
              memory: 64Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /read
              port: 80
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            # periodSeconds: 
            # timeoutSeconds:
            # exec:
            #   command:
            #     - "type command here"
            # tcpSocket:
            #   port: 5000
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: Mongo_User
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: Mongo_Password
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      # imagePullSecrets:
      #   - name: acr-kubedevjesf
