apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pvc-sc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  hostPath:
    path: "/volumes/mongodb"
