apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc-sc
  namespace: pedelogo
spec:
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default
